config/routes.rb
Rails.application.routes.draw do
  resources :samples
  devise_for :users
	root 'pages#homepage', as: 'homepage'
  get '/loading' => 'pages#loading', as: 'loading'
  get '/howto' => 'pages#howto', as: 'howto'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sample.rb
class Sample < ApplicationRecord
  belongs_to :user
  has_one_attached :audio 
  validates :title, presence: true
  validate :sample_type
  public
  def audio_on_disk
    ActiveStorage::Blob.service.send(:path_for, audio.key)
  end
  
  private
  def sample_type
    if audio.attached? == false
      errors.add(:audio, "Select a wav file")
    end
    
  if audio.attached? == true
    if !audio.content_type.in?(%('audio/x-wav'))
      errors.add(:audio, "needs to be a wav file")
    end
   end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :samples
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def homepage
		if (Dir.glob(File.join('app/assets/temp', '*')).select { |file| File.file?(file) }.count) == 36
			@samplemode = 1
		else
			@samplemode = 0
		end
	end

	def howto
	end
	
	def loading
		@yuut = params[:yeet]
	end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /samples
  # GET /samples.json
  def index
    @samples = current_user.samples
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
  end

  # GET /samples/new
  def new
    @sample = Sample.new
  end

  # GET /samples/1/edit
  def edit
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.new(sample_params)
    if current_user
      @sample.user_id =  current_user.id
    end

    if sample_params[:audio]
      @audio = sample_params[:audio]
    else
      @audio = nil
    end

    respond_to do |format|
      if @sample.save and @sample.audio.attach(@audio)
        format.html { redirect_to @sample, notice: 'Sample was successfully created.' }
        format.json { render :show, status: :created, location: @sample }
      else
        format.html { render :new }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samples/1
  # PATCH/PUT /samples/1.json
  def update
    respond_to do |format|
      if @sample.update(sample_params)
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { render :show, status: :ok, location: @sample }
      else
        format.html { render :edit }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample.destroy
    respond_to do |format|
      format.html { redirect_to samples_url, notice: 'Sample was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample
      @sample = Sample.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_params
      params.require(:sample).permit(:title, :user_id, :audio)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>kTunes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<header>
  		<div class="headerimage"></div>
  		<div class="logodiv">
  		<%= link_to(image_tag("logo.png", :class => "logoimage"), homepage_path) %>
  			<nav align=center>
  				<%= link_to 'How to use', howto_path %>
          <% if current_user%>
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
          <%= link_to 'Samples', samples_path%>
          <% else %>
  				<%= link_to 'Register', new_user_registration_path %>
          <%= link_to 'Sign in', new_user_session_path %>
          <% end %>
          
  			</nav>
        <%= render 'layouts/alerts' %>
  		</div>
  	</header>
    <%= yield %>
  </body>
</html>

app/views/pages/homepage.html.erb
<div id="space01"></div>

<div class="keyboard">
	<div class="keyboard_top">
		<h2>kTunes</h2>
		<button onmousedown="setmode()" id="keyboardmode">Toggle Sample Mode</button>
	</div>
	<div class="keyboard_keys">
		<% letters = ['8', '9', '0', 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', 'a', 's', 'd', 'f', 'g', 'h', 'j', 'k'] %>
		
		<div class="keyboard_black_keys"><% for k in (0..14) %><button onmousedown="playkey(<%= k %>, 0)" id="<%= "bk#{k}" %>"></button><% end %></div>
		<div class="keyboard_white_keys"><% for c in (0..20)%><button onmousedown="playkey(<%= c %>, 1)"><i class="keyboardletters"><%= letters[c] %></i></button><% end %></div>
	</div>
	
	<% for i in (1..21) %>
	<audio id="<%= "w#{i}" %>">
		<source src=<%= asset_path("#{i}.ogg") %> type="audio/ogg">
	</audio>
	<% end %>
	
	<% for j in (100..114) %>
	<audio id="<%= "b#{j}" %>">
		<source src=<%= asset_path("#{j}.ogg") %> type="audio/ogg">
	</audio>
	<% end %>
	
	<% if @samplemode == 1 %>
		<% for i in (1..21) %>
			<% if i == 1 %>
				<audio id="<%= "ws#{i}" %>">
					<source src=<%= asset_path("sample.wav") %> type="audio/wav">
				</audio>
			<% else %>
				<audio id="<%= "ws#{i}" %>">
					<source src=<%= asset_path("#{i}.wav") %> type="audio/wav">
				</audio>
			<% end %>
		<% end %>
		
		<% for j in (100..114) %>
		<audio id="<%= "bs#{j}" %>">
			<source src=<%= asset_path("#{j}.wav") %> type="audio/wav">
		</audio>
		<% end %>
	<% end %>
	
	<script>
		var samplemode = <%= @samplemode %>;
		var currentmode = 0;
		function playkey(key, color){
			var keyaud;
			if(color == 0) {
				if(currentmode == 0) {
					keyaud = document.getElementById("b" + (key + 100));
					keycopy = keyaud.cloneNode(true);
					keycopy.position = 0;
					keycopy.play();
				}
				
				else {
					keyaud = document.getElementById("bs" + (key + 100));
					keycopy = keyaud.cloneNode(true);
					keycopy.position = 0;
					keycopy.play();
				}
			}
			
			
			else {
				if(currentmode == 0) {
					keyaud = document.getElementById("w" + (key + 1));
					keycopy = keyaud.cloneNode(true);
					keycopy.position = 0;
					keycopy.play();
				}
				
				else {
					keyaud = document.getElementById("ws" + (key + 1));
					keycopy = keyaud.cloneNode(true);
					keycopy.position = 0;
					keycopy.play();
				}
			}
		}
		
		document.onkeydown = function(e) {
			e = e || window.event;
			
			if(e.key == "8") {
				playkey(0, 1);
			}
			if(e.key == "9") {
				playkey(1, 1);
			}
			if(e.key == "0") {
				playkey(2, 1)
			}
			if(e.key == "q") {
				playkey(3, 1)
			}
			if(e.key == "w") {
				playkey(4, 1)
			}
			if(e.key == "e") {
				playkey(5, 1)
			}
			if(e.key == "r") {
				playkey(6, 1)
			}
			if(e.key == "t") {
				playkey(7, 1)
			}
			if(e.key == "y") {
				playkey(8, 1)
			}
			if(e.key == "u") {
				playkey(9, 1)
			}
			if(e.key == "i") {
				playkey(10, 1)
			}
			if(e.key == "o") {
				playkey(11, 1)
			}
			if(e.key == "p") {
				playkey(12, 1)
			}
			if(e.key == "a") {
				playkey(13, 1)
			}
			if(e.key == "s") {
				playkey(14, 1)
			}
			if(e.key == "d") {
				playkey(15, 1)
			}
			if(e.key == "f") {
				playkey(16, 1)
			}
			if(e.key == "g") {
				playkey(17, 1)
			}
			if(e.key == "h") {
				playkey(18, 1)
			}
			if(e.key == "j") {
				playkey(19, 1)
			}
			if(e.key == "k") {
				playkey(20, 1)
			}
			if(e.key == "*") {
                playkey(0, 0)
            }
            if(e.key == "(") {
                playkey(1, 0)
            }
            if(e.key == "Q") {
                playkey(2, 0)
            }
            if(e.key == "W") {
                playkey(3, 0)
            }
            if(e.key == "E") {
                playkey(4, 0)
            }
            if(e.key == "T") {
                playkey(5, 0)
            }
            if(e.key == "Y") {
                playkey(6, 0)
            }
            if(e.key == "I") {
                playkey(7, 0)
            }
            if(e.key == "O") {
                playkey(8, 0)
            }
            if(e.key == "P") {
                playkey(9, 0)
            }
            if(e.key == "S") {
                playkey(10, 0)
            }
            if(e.key == "D") {
                playkey(11, 0)
            }
            if(e.key == "G") {
                playkey(12, 0)
            }
            if(e.key == "H") {
                playkey(13, 0)
            }
            if(e.key == "J") {
                playkey(14, 0)
            }
		}
		
		function setmode() {
			if(samplemode == 0) {
				alert("No sample loaded.");
			}
			
			else {
				var modebutton = document.getElementById("keyboardmode");
				if(currentmode == 0) {
					currentmode = 1;
					modebutton.textContent = "Untoggle Sample Mode";
				}
				
				else {
					currentmode = 0;
					modebutton.textContent = "Toggle Sample Mode";
				}
			}
		}
	</script>
	
</div>

app/views/pages/loading.html.erb
	<% x = @yuut %>

	<%FileUtils.cp(x, 'app/assets/temp/sample.wav')%>
	
	<% x = 2 %>
	<% y = 100 %>
	<% for c in (1..35) %>
		<% case c %>
			<% when 2, 4, 5, 7, 9, 11, 12, 14, 16, 17, 19, 21, 23, 24, 26, 28, 29, 31, 33, 35 %>
				<% system("app/assets/rubberband/rubberband.linux --pitch #{c} -q 'app/assets/temp/sample.wav' 'app/assets/temp/#{x}.wav'");x = x + 1 %>
			<% when 1, 3, 6, 8, 10, 13, 15, 18, 20, 22, 25, 27, 30, 32, 34 %>
				<% system("app/assets/rubberband/rubberband.linux --pitch #{c} -q 'app/assets/temp/sample.wav' 'app/assets/temp/#{y}.wav'");y = y + 1 %>
		<% end %>
	<% end %>
	
	<h1 align=center class="h1">Loading your sample</h1>
	<h1 align=center class="h1">Please, wait...</h1>
	<div class="loader"><div class="loader2"></div></div>

	<script>
		setTimeout(function() {
			window.location = "<%= homepage_path %>";
		}, 5000);
	</script>

app/views/pages/registerpage.html.erb
<h1>Users</h1> 

app/views/samples/_form.html.erb
<%= form_with(model: sample, local: true) do |form| %>
  <% if sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% sample.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div>
  <%= form.label :audio%>
  <%= form.file_field :audio%>
  </div>

  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/samples/edit.html.erb
<div class="authbodydiv">
	<div class="samplediv" id="usedform2">
		<h1 class="authtitle">Editing Sample</h1>
		<div class="formdiv"
			<%= render 'form', sample: @sample %>

			<div class="troublesomelinks"><%= link_to 'Show', @sample %> |
			<%= link_to 'Back', samples_path %></div>
			
		</div>
	</div>
</div>

app/views/samples/index.html.erb
<div class="authbodydiv">
	<div class="samplediv">
		<p id="notice"><%= notice %></p>

		<h1 class="authtitle">Samples</h1>

		<tbody>
			<% if current_user.samples != [] %>
				<% current_user.samples.each do |sample| %>
				<tr>
					<div class="sampletitle"><td><%= sample.title %></td></div>

					<div class="samplecommands">
						<td><%= link_to 'Show', sample %></td>
						<td><%= link_to 'Edit', edit_sample_path(sample) %></td>
						<td><%= link_to 'Destroy', sample, method: :delete, data: { confirm: 'Are you sure?' } %></td>
						<% yeet = sample.audio_on_disk%>
						<td><%= link_to 'Load Sample', loading_path(:yeet => yeet) %> </td>
						
					</div>
					
			</tr>
				<% end %>
    		<% else %>
				<h2> Create a sample!</h2>
			<% end %>
		</tbody>
		</table>

	<br>

	<div class="troublesomelinks" id="newsample"><%= link_to 'New Sample', new_sample_path %></div>
	</div>
</div>

app/views/samples/new.html.erb
<div class="authbodydiv">
	<div class="samplediv" id="usedform">
		<h1 class="authtitle">New Sample</h1>
			<div class="formdiv">
				<%= render 'form', sample: @sample %>

				<div class="troublesomelinks"><%= link_to 'Back', samples_path %></div>
			</div>
	</div>
</div>

app/views/samples/show.html.erb
<div class="authbodydiv">
	<div class="samplediv" id="showsample">
		<p id="notice"><%= notice %></p>

		<p id="p">
  			<h2 class="authtitle" id="sampletitle">Title:</h2>
			<div id="samplename"><%= @sample.title %></div>
		</p>


	<div class="troublesomelinks"><%= link_to 'Download', @sample.audio%> |
	<%= link_to 'Edit', edit_sample_path(@sample) %> |
	<%= link_to 'Back', samples_path %></div>
	</div>
</div>